export {
  matchesProjectBrandingVocabulary,
  matchesMetadataFooterVocabulary,
  matchesAdministrativeTitleMetadata,
  matchesReviewReferenceMetadata,
  matchesProjectFieldMetadata,
  matchesJobNumberMetadata,
  matchesVendorReferencePageMetadata,
  isMetadataBoxFooterLine,
  isMetadataLabelOnlyText,
  isMetadataBoxTitleFragment,
  isCompactStampContinuationFragment,
  shouldPreferOcrCompactAnchorOverPdfPair,
  shouldPreferOcrTitleOverPdfScaleStub,
  isPairedWithinMetadataBox,
  hasViableCompactStampStructure,
  getStyleProfileForRegion,
  getTextualSheetNumberRejectPenalty,
  getTextualTitleRejectPenalty,
  getMetadataBoxFamilyFromBbox,
  getMetadataBoxRejectReason,
  isRepeatedProjectBrandingTitle,
} from "./core";
